/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.DAO.Banco;
import controller.LoginController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author leodi
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     * @throws java.text.ParseException
     */
    public Login() throws ParseException {
        initComponents();
        controller = new LoginController(this); // Eu quero uma variável Controller que vai do tipo Controller e vou me passar como parâmetro por conta que eu sou do tipo Login
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoSenha = new javax.swing.JTextField();
        botaoEntrarLogin = new javax.swing.JToggleButton();
        campoUsuario = new javax.swing.JTextField();
        textoSenha = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JLabel();
        textoLogin = new javax.swing.JLabel();
        imagemLogin = new javax.swing.JLabel();
        arteLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 230, 40));

        botaoEntrarLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEntrarLogin.setText("ENTRAR");
        botaoEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEntrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 230, 40));

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 230, 40));

        textoSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoSenha.setForeground(new java.awt.Color(255, 255, 255));
        textoSenha.setText("Senha");
        getContentPane().add(textoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, -1));

        textoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoUsuario.setText("Usuário");
        getContentPane().add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        textoLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        textoLogin.setForeground(new java.awt.Color(255, 255, 255));
        textoLogin.setText("Login");
        getContentPane().add(textoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        imagemLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/painel-login.png"))); // NOI18N
        getContentPane().add(imagemLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 540, 480));

        arteLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(arteLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, 1206));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarLoginActionPerformed
        // Executa quando clico no botão
        this.controller.entrarNoSistema();
        // Pegaremos usuário com campoUsuario.getText()
        // Pegaremos usuário com campoSenha.getPassword()
    }//GEN-LAST:event_botaoEntrarLoginActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Login().setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arteLogin;
    private javax.swing.JToggleButton botaoEntrarLogin;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel imagemLogin;
    private javax.swing.JLabel textoLogin;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel textoUsuario;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensage) {
        JOptionPane.showMessageDialog(null, mensage);
    }

    public JTextField getCampoSenha() {
        return campoSenha;
    }

    public void setCampoSenha(JPasswordField campoSenha) {
        this.campoSenha = campoSenha;
    }

    public JTextField getCampoUsuario() {
        return campoUsuario;
    }

    public void setCampoUsuario(JTextField campoUsuario) {
        this.campoUsuario = campoUsuario;
    }
    
    
}
